import {useState} from 'react';import {Link} from 'react-router-dom';import {useData} from '../store';import {src} from '../img';import Icon from '../components/Icon';
const feats=[['shield','Premium Quality','Science backed & tested'],['leaf','Safe & Natural','Made with natural ingredients'],['truck','Fast Delivery','Quick & reliable shipping'],['award','Trusted by Customers','Satisfaction guaranteed']];
const pc=[['grid','All Products'],['shield','Healthcare'],['heart','Wellness'],['users','Mobility Aids'],['target','Wearables'],['leaf','Personal Care']];
const sc=[['grid','All Services'],['monitor','Web Development'],['phone','App Development'],['pen','UI/UX Design'],['layers','Digital Solutions'],['clock','Maintenance']];
function Side({items,cur,set}){return <aside>{items.map(([i,t],k)=><button key={t} className={cur===t?'on':''} onClick={()=>set(t)}><Icon n={i} s={16}/> {t}<span>›</span></button>)}</aside>}
export default function Store(){
 const {data:d}=useData();const [a,setA]=useState('All Products');const [b,setB]=useState('All Services');const [cart,setCart]=useState([]);
 const P=d.storeProducts.filter(p=>a==='All Products'||p.cat===a),D=d.digital.filter(p=>b==='All Services'||p.cat===b);
 return <main><section className="phero"><div className="wrap split"><div><small className="tag"><Link to="/">HOME</Link> / STORE</small><h1>Our <em>Store</em></h1><p>Explore our range of biotechnology products and healthcare solutions – crafted with science, care and innovation.</p><a href="#shop" className="btn dark">Shop Now →</a></div><img src={src('s3')} alt="" className="pimg sm"/></div></section>
  <section className="wrap"><div className="strip">{feats.map(([i,t,s])=><div key={t}><span className="ic"><Icon n={i}/></span><div><b>{t}</b><small>{s}</small></div></div>)}</div></section>
  <section className="wrap store" id="shop"><Side items={pc} cur={a} set={setA}/><div><h6 className="ttl"><span>BIOTECH & HEALTHCARE PRODUCTS</span></h6><div className="pgrid">{P.map(p=><div className="card pcard" key={p.id}><img src={src(p.img)} alt={p.name}/><h5>{p.name}</h5><small>{p.sub}</small><b>{p.price}</b><button className="btn dark" onClick={()=>setCart(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}>{cart.includes(p.id)?'Added ✓':'Add to Cart'} <Icon n="cart" s={13}/></button></div>)}{!P.length&&<p>No products in this category yet.</p>}</div></div></section>
  <section className="wrap store"><Side items={sc} cur={b} set={setB}/><div><h6 className="ttl"><span>DIGITAL PRODUCTS & SERVICES</span></h6><div className="pgrid">{D.map(p=><div className="card pcard" key={p.id}><img src={src(p.img)} alt={p.name}/><h5>{p.name}</h5><small>{p.sub}</small><b>{p.price}</b><Link to="/contact" className="btn soft">Explore</Link></div>)}{!D.length&&<p>No services in this category yet.</p>}</div></div></section>
  <section className="wrap"><div className="cta"><span className="ic big"><Icon n="box" s={28}/></span><div><h2>Can't find what you're looking for?</h2><p>We can build custom solutions tailored to your needs.</p></div><Link to="/contact" className="btn light">Request Custom Solution →</Link></div></section></main>;
}
